"""adding achievements to user

Revision ID: 23d4d4aa2f43
Revises: 97701ad9c4f8
Create Date: 2023-10-21 10:21:14.958729

"""
from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "23d4d4aa2f43"
down_revision: Union[str, None] = "97701ad9c4f8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "User", sa.Column("achievements", sqlmodel.sql.sqltypes.AutoString(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("User", "achievements")
    # ### end Alembic commands ###
