"""adding double bird highscore

Revision ID: 37ce7de0d21d
Revises: 23d4d4aa2f43
Create Date: 2023-10-26 21:18:07.670020

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "37ce7de0d21d"
down_revision: Union[str, None] = "23d4d4aa2f43"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("User", sa.Column("best_score_single_bird", sa.Integer(), nullable=False))
    op.add_column("User", sa.Column("best_score_double_bird", sa.Integer(), nullable=False))
    op.drop_column("User", "best_score")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "User", sa.Column("best_score", sa.INTEGER(), autoincrement=False, nullable=False)
    )
    op.drop_column("User", "best_score_double_bird")
    op.drop_column("User", "best_score_single_bird")
    # ### end Alembic commands ###
