"""changed email to hash

Revision ID: 5e102dabccfd
Revises: 3292f556e594
Create Date: 2025-01-12 14:47:11.501616

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '5e102dabccfd'
down_revision: Union[str, None] = '3292f556e594'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('email_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.create_index('user_index', 'User', ['email_hash', 'origin'], unique=True)
    op.drop_column('User', 'email')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index('user_index', table_name='User')
    op.drop_column('User', 'email_hash')
    # ### end Alembic commands ###
