"""adding leaderboard

Revision ID: 97701ad9c4f8
Revises: a2c455270da0
Create Date: 2023-10-12 20:07:46.266489

"""
from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "97701ad9c4f8"
down_revision: Union[str, None] = "a2c455270da0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "LeaderboardOnePlayer",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("score", sa.Integer(), nullable=False),
        sa.Column("user_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["User.id"], name=op.f("fk_LeaderboardOnePlayer_user_id_User")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_LeaderboardOnePlayer")),
    )
    op.create_index(
        op.f("ix_LeaderboardOnePlayer_timestamp"),
        "LeaderboardOnePlayer",
        ["timestamp"],
        unique=False,
    )
    op.create_table(
        "LeaderboardTwoPlayer",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("score", sa.Integer(), nullable=False),
        sa.Column("user_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["User.id"], name=op.f("fk_LeaderboardTwoPlayer_user_id_User")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_LeaderboardTwoPlayer")),
    )
    op.create_index(
        op.f("ix_LeaderboardTwoPlayer_timestamp"),
        "LeaderboardTwoPlayer",
        ["timestamp"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_LeaderboardTwoPlayer_timestamp"), table_name="LeaderboardTwoPlayer")
    op.drop_table("LeaderboardTwoPlayer")
    op.drop_index(op.f("ix_LeaderboardOnePlayer_timestamp"), table_name="LeaderboardOnePlayer")
    op.drop_table("LeaderboardOnePlayer")
    # ### end Alembic commands ###
