"""platform achievement tracking

Revision ID: 9d7088dcfee1
Revises: 37ce7de0d21d
Create Date: 2023-11-18 13:12:03.371124

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9d7088dcfee1"
down_revision: Union[str, None] = "37ce7de0d21d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "User", sa.Column("platform", sa.Integer(), nullable=False, server_default=str(0))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("User", "platform")
    # ### end Alembic commands ###
