"""bird to butterfly

Revision ID: d3ffe081e45a
Revises: 9d7088dcfee1
Create Date: 2024-07-19 12:06:25.452648

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3ffe081e45a'
down_revision: Union[str, None] = '9d7088dcfee1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('best_score_single_butterfly', sa.Integer(), nullable=False))
    op.add_column('User', sa.Column('best_score_double_butterfly', sa.Integer(), nullable=False))
    op.drop_column('User', 'best_score_single_bird')
    op.drop_column('User', 'best_score_double_bird')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('best_score_double_bird', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('User', sa.Column('best_score_single_bird', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('User', 'best_score_double_butterfly')
    op.drop_column('User', 'best_score_single_butterfly')
    # ### end Alembic commands ###
