"""remove foreign key reference on leaderboard

Revision ID: e69925457e1f
Revises: 5e102dabccfd
Create Date: 2025-01-12 22:22:11.764043

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e69925457e1f'
down_revision: Union[str, None] = '5e102dabccfd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_LeaderboardOnePlayer_user_id_User', 'LeaderboardOnePlayer', type_='foreignkey')
    op.drop_constraint('fk_LeaderboardTwoPlayer_user_id_User', 'LeaderboardTwoPlayer', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('fk_LeaderboardTwoPlayer_user_id_User', 'LeaderboardTwoPlayer', 'User', ['user_id'], ['id'])
    op.create_foreign_key('fk_LeaderboardOnePlayer_user_id_User', 'LeaderboardOnePlayer', 'User', ['user_id'], ['id'])
    # ### end Alembic commands ###
